- lib.typ
When I install the Sans Source Pro font from the linked repository on Windows 10 they appear as "Source Sans 3".
This PR adds this name to the font parameter.
> Support Source Sans Pro font with alternative name

- .github/workflows/build-documentation.yml
- lib.typ
Made `author.address` optional. Also improved how other fields in the `author` dictionary are checked so they can be omitted completely if the user so chooses. Currently they must be left empty to be omitted.
Fixes #36
> Mmake address optional

- .github/workflows/build-documentation.yml
- lib.typ
For chinese and japanese, don't use a space between the firstname and lastname.
Fixes #37
> No space between first and last name for Japanese and Chinese languages

- README.md
As a new user (to typst and to modern-cv), I copy-pasted the example, got it working, and then started modifying using features released post 0.1.0 (such as `colored-headers`). It took me a while to figure out that the import is of a very old version.
PS: thank you for this package, works very well.
> Update README example to use 0.4.0

- lib.typ
- template/resume.typ
Thank you so much for the template. It’s the best one I’ve found and fits my needs perfectly.
Following #45 , this PR added the [ORCID](https://orcid.org/) link and icon, which might be convenient for those, including myself, who use ORCID.
> Add ORCID links with icons in the header 

- lib.typ
to avoid the empty line when both date and description are set to empty string or not present
> Hide date and description when both are empty

- lib.typ
- template/coverletter.typ
- template/resume.typ
You can now specify the font for the resume and coverletter.
Fixes #50 
Example:
```typst
#show: coverletter.with(
author: (
firstname: "John",
lastname: "Smith",
email: "js@gmail.com",
homepage: "https://example.com",
phone: "(+1) 111-111-1111",
github: "DeveloperPaul123",
linkedin: "John Smith",
address: "111 Example St. Apt. 111, Example City, EX 11111",
positions: (
"Software Engineer",
"Full Stack Developer",
),
),
profile-picture: image("./profile.png"),
language: "en",
font: "Times New Roman"
)
```
> Add font input for resume and coverletter

- lib.typ
- template/coverletter.typ
- template/resume.typ
> feat: add ability to show/hide footer

- lib.typ
These are small quick changes to add some parity between the cover letter and resume header.
Specifically, I noticed that the cover letter used the author name in the LinkedIn field (e.g., John Doe) whereas the resume kept the id (e.g., johndoe). Also, cover letter lacked OrcID so I just copied/pasted that down to the cover letter section as well. 
My solutions are novice copy/paste edits, and I'm not familiar with this syntax, but it did work in my own testing. Please carefully review and feel free to add/edit/ignore.
I'm sure there's other fields that don't match up exactly, but those are the two I use. Cheers and great work on this!
> Formatting parity between cover letter and resume author info

- lib.typ
- template/coverletter.typ
You can now supply your own text body/function for the letter closing (what goes after the signature)
Closes #60
> Make closing remark in letter optional

- lib.typ
There was an issue that sometimes the contacts didn't fully align to the right. 
I simplified the separation process by pushing each used contact field to the contacts list and then merging them together with the `.join(separator)` Typst function.
This should make it more flexible for the different variations of selected contacts fields.
> Fix bad alignment of the contacts

- lib.typ
Use specified (or default) font also for the name in the header, instead of the hardcoded "Roboto"
> Use provided font for header name

- README.md
- lib.typ
- template/resume.typ
Hi there,
This is my attempt to add a profile picture in the resume template (see #56).
Here is the result:
Thanks,
Clément
> Add the ability to set a profile picture in resume

- lib.typ
close #86. Allow font awesome icon in the heading like this:
```
= #fa-icon("cogs", fill: blue, size: 12pt) Experience
```
and output:
> fix: allow font awesome icon in heading

- lang.toml
- lib.typ
- template/coverletter.typ
> feat: make "job application for" text translatable

- lib.typ
Added disable-smallcaps parameter to both templates with a default value of false.
Modified all smallcaps usage to be conditional based on the parameter:
- Resume positions
- Level 3 headings
- Resume and coverletter footers
- Company names in hiring entity info
> feat: add disable-smallcaps option

- README.md
In the README and therefore generated docs in Typst Universe there there is `page-size`, however template uses `paper-size`.
> fix: use paper-size in docs

- lib.typ
comparing strings with types is deprecated
This PR migrates to the new way of comparing types.
> Use type literals for comparison

- lib.typ
- template/coverletter2.typ
- template/resume.typ
Hi, and thanks for the great `modern-cv` Typst library. It has been a pleasure to use it!
This PR adds support for a single `custom` field in the `author` metadata, allowing users to define a non-standard contact entry such as a blog, YouTube channel, or other link.
```typst
custom: (				// optional
text: "Youtube Channel",		// required
icon: "youtube",			// optional
link: "http://example.com",		// optional
show-in-contacts: true,		// optional
)
> feat: Add support for `custom` author entry

- lib.typ
Update to #40
Can refer to https://github.com/ice-kylin/typst-cv-miku
Ideally, the linkedin name shouldn't follow the specified first name and last name since most likely even in other languages, it could be in english.
> Fix zh/jp name order

- lib.typ
I discovered typst and your modern-cv lib today. I found the need for adding my signature above my name in the signature block of the cover letter.
I tried adding a type check, but that broke adding the image.
> [FEATURE] Possibility to add author.signature as image to be added above author's name in signature block.
